/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ThemeGroup: typeof import('./src/components/ThemeGroup/index.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarButtonGroup: typeof import('@varlet/ui')['_ButtonGroupComponent']
  }
}
